spring:
  mail:
    host: smtp.gmail.com
    username: r.alexisngoga20@gmail.com
    password: chsuarudaqopygpe
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true